// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAScKANXeaLyxc9mVRkHtdsH4MDWCjBYzg',
    appId: '1:31364879032:web:03865d20ee461cec455a4d',
    messagingSenderId: '31364879032',
    projectId: 'food-f6402',
    authDomain: 'food-f6402.firebaseapp.com',
    storageBucket: 'food-f6402.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHOy1OjeCgRtgrm6UX3xkAGOwA8nOJGg',
    appId: '1:31364879032:android:fdef27ec43bcffd6455a4d',
    messagingSenderId: '31364879032',
    projectId: 'food-f6402',
    storageBucket: 'food-f6402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC74LDfJZvI436h_1n8c5v8kL0xWGcFRMM',
    appId: '1:31364879032:ios:f9115e49b9ab933e455a4d',
    messagingSenderId: '31364879032',
    projectId: 'food-f6402',
    storageBucket: 'food-f6402.firebasestorage.app',
    iosBundleId: 'com.example.fodd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC74LDfJZvI436h_1n8c5v8kL0xWGcFRMM',
    appId: '1:31364879032:ios:f9115e49b9ab933e455a4d',
    messagingSenderId: '31364879032',
    projectId: 'food-f6402',
    storageBucket: 'food-f6402.firebasestorage.app',
    iosBundleId: 'com.example.fodd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAScKANXeaLyxc9mVRkHtdsH4MDWCjBYzg',
    appId: '1:31364879032:web:315f2559b629ae2a455a4d',
    messagingSenderId: '31364879032',
    projectId: 'food-f6402',
    authDomain: 'food-f6402.firebaseapp.com',
    storageBucket: 'food-f6402.firebasestorage.app',
  );
}
